#!/usr/bin/perl -w

use strict;

use File::Basename;
use PDF::API2;
use YAML;

my $metafile = $ARGV[0];

die "Please specify a .pdf.stitch to process!\n" unless defined $metafile;
die "Can't open $metafile!\n" unless -r $metafile;

my $meta = YAML::LoadFile($metafile);

my $inpdf = PDF::API2->open($meta->{input});
my $cropped = PDF::API2->new();

foreach my $nr (@{$meta->{pageorder}})
{
    print "Cropping page $nr...\n";
    my $page = $cropped->import_page($inpdf, $nr, 0);
    my ($llx, $lly, $urx, $ury);
    $llx = $meta->{x} + $meta->{pageoffsets}->{$nr}->{x};
    $lly = $meta->{y} + $meta->{pageoffsets}->{$nr}->{y};
    $urx = $llx + $meta->{width};
    $ury = $lly + $meta->{height};
    $page->cropbox($llx, $lly, $urx, $ury);
}

$cropped->saveas(basename($meta->{input}, '.pdf') . '-cropped.pdf');

